version: '3'
services:
    pypi-mirror:
        image: pypa/bandersnatch
        volumes:
            - ./bandersnatch.conf:/conf/bandersnatch.conf
            - ${MIRROR_DIR}:/data/pypi/
        restart: always
        deploy:
            resources:
                limits:
                    memory: ${MAX_DOCKER_MEMORY}
