version: '3'
services:
    npm-mirror:
        build: ./
        image: osssanitizer/npm-mirror
        volumes:
            - ${MIRROR_DIR}:/data/npm/
        environment:
            - INIT=${INIT}
        restart: always
        deploy:
            resources:
                limits:
                    memory: ${MAX_DOCKER_MEMORY}
