version: '3'
services:
    redis:
        image: 'redis:3.2.7'
        ports:
            - "6379:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD}

    postgres:
        image: postgres:9.6
        ports:
            - "5432:5432"
        command: postgres -c max_connections=100000
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        # Uncomment these lines to persist data on the local filesystem.
        #     - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: malossscan/maloss:latest
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - AIRFLOW_DAGS=${AIRFLOW_DAGS}
            - AIRFLOW__WEBSERVER__AUTHENTICATE=${AIRFLOW__WEBSERVER__AUTHENTICATE}
            - AIRFLOW__WEBSERVER__AUTH_BACKEND=${AIRFLOW__WEBSERVER__AUTH_BACKEND}
            - AIRFLOW__WEBSERVER__USERNAME=${AIRFLOW__WEBSERVER__USERNAME}
            - AIRFLOW__WEBSERVER__EMAIL=${AIRFLOW__WEBSERVER__EMAIL}
            - AIRFLOW__WEBSERVER__PASSWORD=${AIRFLOW__WEBSERVER__PASSWORD}
            - AIRFLOW__WEBSERVER__BASE_URL=${AIRFLOW__WEBSERVER__BASE_URL}
            - AIRFLOW__CORE__PARALLELISM=${AIRFLOW__CORE__PARALLELISM}
            - AIRFLOW__CORE__DAG_CONCURRENCY=${AIRFLOW__CORE__DAG_CONCURRENCY}
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/maloss/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: malossscan/maloss:latest
        restart: always
        depends_on:
            - postgres
            - redis
        # volumes:
        #     - ./requirements.txt:/requirements.txt
        environment:
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "5555:5555"
        command: flower --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}

    scheduler:
        image: malossscan/maloss:latest
        restart: always
        depends_on:
            - webserver
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - AIRFLOW_DAGS=${AIRFLOW_DAGS}
            - AIRFLOW__CORE__PARALLELISM=${AIRFLOW__CORE__PARALLELISM}
            - AIRFLOW__CORE__DAG_CONCURRENCY=${AIRFLOW__CORE__DAG_CONCURRENCY}
        command: scheduler

