version: '3'
services:
    postgres:
        image: postgres:9.6
        command: postgres -c max_connections=10000
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    webserver:
        image: malossscan/maloss
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - AIRFLOW_DAGS=${AIRFLOW_DAGS}
            - AIRFLOW__WEBSERVER__AUTHENTICATE=${AIRFLOW__WEBSERVER__AUTHENTICATE}
            - AIRFLOW__WEBSERVER__AUTH_BACKEND=${AIRFLOW__WEBSERVER__AUTH_BACKEND}
            - AIRFLOW__WEBSERVER__USERNAME=${AIRFLOW__WEBSERVER__USERNAME}
            - AIRFLOW__WEBSERVER__EMAIL=${AIRFLOW__WEBSERVER__EMAIL}
            - AIRFLOW__WEBSERVER__PASSWORD=${AIRFLOW__WEBSERVER__PASSWORD}
            # - AIRFLOW__WEBSERVER__BASE_URL=${AIRFLOW__WEBSERVER__BASE_URL}
            - AIRFLOW__CORE__PARALLELISM=${AIRFLOW__CORE__PARALLELISM}
            - AIRFLOW__CORE__DAG_CONCURRENCY=${AIRFLOW__CORE__DAG_CONCURRENCY}
        volumes:
            - ${METADATA_FOLDER}:/home/maloss/metadata
            - ${RESULT_FOLDER}:/home/maloss/result
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/maloss/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
