version: '3'
services:
    worker:
        image: malossscan/maloss:latest
        restart: always
        volumes:
            - ${METADATA_FOLDER}:/home/maloss/metadata
            - ${RESULT_FOLDER}:/home/maloss/result
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - AIRFLOW_DAGS=${AIRFLOW_DAGS}
            - AIRFLOW__CORE__PARALLELISM=${AIRFLOW__CORE__PARALLELISM}
            - AIRFLOW__CORE__DAG_CONCURRENCY=${AIRFLOW__CORE__DAG_CONCURRENCY}
            - AIRFLOW__CELERY__WORKER_CONCURRENCY=${AIRFLOW__CELERY__WORKER_CONCURRENCY}
        ports:
            - "8793:8793"
        command: worker
        deploy:
            resources:
                limits:
                    memory: ${MAX_DOCKER_MEMORY}

